// AUTO-GENERATED by scripts/gen-exercise-images-map.js — do not edit by hand.
// Static require() map of Flux-generated exercise hero images, keyed by catalog id.
import { ImageSourcePropType } from 'react-native';

export const EXERCISE_IMAGES: Record<string, ImageSourcePropType> = {
  'ex_001': require('../../assets/exercises/ex_001.jpg'),
  'ex_002': require('../../assets/exercises/ex_002.jpg'),
  'ex_003': require('../../assets/exercises/ex_003.jpg'),
  'ex_004': require('../../assets/exercises/ex_004.jpg'),
  'ex_005': require('../../assets/exercises/ex_005.jpg'),
  'ex_006': require('../../assets/exercises/ex_006.jpg'),
  'ex_007': require('../../assets/exercises/ex_007.jpg'),
  'ex_008': require('../../assets/exercises/ex_008.jpg'),
  'ex_009': require('../../assets/exercises/ex_009.jpg'),
  'ex_010': require('../../assets/exercises/ex_010.jpg'),
  'ex_011': require('../../assets/exercises/ex_011.jpg'),
  'ex_012': require('../../assets/exercises/ex_012.jpg'),
  'ex_013': require('../../assets/exercises/ex_013.jpg'),
  'ex_014': require('../../assets/exercises/ex_014.jpg'),
  'ex_015': require('../../assets/exercises/ex_015.jpg'),
  'ex_016': require('../../assets/exercises/ex_016.jpg'),
  'ex_017': require('../../assets/exercises/ex_017.jpg'),
  'ex_018': require('../../assets/exercises/ex_018.jpg'),
  'ex_019': require('../../assets/exercises/ex_019.jpg'),
  'ex_020': require('../../assets/exercises/ex_020.jpg'),
};

/** Hero image for an exercise id, or undefined if none was generated. */
export function getExerciseImage(exerciseId?: string): ImageSourcePropType | undefined {
  if (!exerciseId) return undefined;
  return EXERCISE_IMAGES[exerciseId];
}
